package com.example.broilerfarm.application.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class ConsumptionSheetLineDto {
    private Long id;
    private Long consumptionSheetId;
    private Long consumableId;
    private BigDecimal quantityConsumed;
    private LocalTime consumptionMoment;
    private BigDecimal consumptionPerBird;
    private String notes;
    private Boolean autoGenerated;
}
