package com.example.broilerfarm.infrastructure.persistence.repositories;

import com.example.broilerfarm.domain.entities.ConsumptionSheetLine;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ConsumptionSheetLineRepository extends JpaRepository<ConsumptionSheetLine, Long> {

    List<ConsumptionSheetLine> findByConsumptionSheetId(Long sheetId);

    List<ConsumptionSheetLine> findByAutoGeneratedTrue();

    @Query("SELECT csl FROM ConsumptionSheetLine csl WHERE csl.consumptionSheet.id = :sheetId " +
            "AND csl.consumable.id = :consumableId")
    List<ConsumptionSheetLine> findBySheetIdAndConsumableId(
            @Param("sheetId") Long sheetId,
            @Param("consumableId") Long consumableId
    );

    @Query("SELECT csl FROM ConsumptionSheetLine csl WHERE csl.consumable.id = :consumableId " +
            "ORDER BY csl.consumptionSheet.sheetDate DESC")
    List<ConsumptionSheetLine> findByConsumableIdOrderByDateDesc(@Param("consumableId") Long consumableId);
}