package com.example.broilerfarm.domain.entities;

import com.example.shared.domain.BaseEntity;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalTime;

@Entity
@Table(name = "consumption_sheet_line")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ConsumptionSheetLine extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "consumption_sheet_id", nullable = false)
    private ConsumptionSheet consumptionSheet;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "consumable_id", nullable = false)
    private Consumable consumable;

    @Column(name = "quantity_consumed", nullable = false, precision = 10, scale = 2)
    private BigDecimal quantityConsumed;

    @Column(name = "feeding_time")
    private LocalTime feedingTime;

    @Column(name = "consumption_per_bird", precision = 10, scale = 4)
    private BigDecimal consumptionPerBird;

    @Column(name = "notes", length = 500)
    private String notes;

    @Column(name = "auto_generated", nullable = false)
    @Builder.Default
    private Boolean autoGenerated = false;

    // ✅ Calcul automat consumption per bird
    public void calculateConsumptionPerBird(Integer birdsAlive) {
        if (birdsAlive == null || birdsAlive == 0) {
            this.consumptionPerBird = BigDecimal.ZERO;
            return;
        }

        this.consumptionPerBird = this.quantityConsumed
                .divide(BigDecimal.valueOf(birdsAlive), 4, RoundingMode.HALF_UP);
    }

    // ✅ Validare cantitate
    public void validate() {
        if (quantityConsumed.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Quantity consumed must be positive");
        }

        if (consumable == null) {
            throw new IllegalStateException("Consumable must be specified");
        }
    }

    // ✅ Marcare ca auto-generată (din TreatmentSheet)
    public void markAsAutoGenerated(String treatmentReference) {
        this.autoGenerated = true;
        this.notes = (this.notes == null ? "" : this.notes + " | ")
                + "Auto-generated from treatment: " + treatmentReference;
    }

    @Transient
    public boolean isFeedLine() {
        return consumable != null && consumable.isFeedType();
    }

    @Transient
    public boolean isMedicationLine() {
        return consumable != null && consumable.isMedication();
    }

    @Transient
    public boolean isAutoGenerated(){
        return this.autoGenerated;
    }
}