package com.example.broilerfarm.domain.entities;

import com.example.broilerfarm.domain.enums.ConsumptionSheetStatus;
import com.example.shared.domain.entity.BaseEntity;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "consumption_sheet")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ConsumptionSheet extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lot_id", nullable = false)
    private ChicksLot lot;

    @Column(name = "sheet_date", nullable = false)
    @Builder.Default
    private LocalDate sheetDate = LocalDate.now();

    @Column(name = "birds_alive", nullable = false)
    private Integer birdsAlive;

    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private ConsumptionSheetStatus status = ConsumptionSheetStatus.DRAFT;

    // ✅ AGGREGATE: ConsumptionSheet conține liniile sale
    @OneToMany(mappedBy = "consumptionSheet", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<ConsumptionSheetLine> consumptionLines = new ArrayList<>();

    // ✅ Business logic pentru gestionarea liniilor
    public void addConsumptionLine(ConsumptionSheetLine line) {
        if (line == null) {
            throw new IllegalArgumentException("Consumption line cannot be null");
        }

        if (this.status == ConsumptionSheetStatus.APPROVED) {
            throw new IllegalStateException("Cannot add lines to an approved consumption sheet");
        }

        consumptionLines.add(line);
        line.setConsumptionSheet(this);
        line.calculateConsumptionPerBird(this.birdsAlive);
    }

    public void removeConsumptionLine(ConsumptionSheetLine line) {
        if (this.status == ConsumptionSheetStatus.APPROVED) {
            throw new IllegalStateException("Cannot remove lines from an approved consumption sheet");
        }

        consumptionLines.remove(line);
        line.setConsumptionSheet(null);
    }

    // ✅ Recalculare consumption per bird pentru toate liniile
    public void recalculateAllLines() {
        consumptionLines.forEach(line -> line.calculateConsumptionPerBird(this.birdsAlive));
    }

    // ✅ Finalizare sheet
    public void submit() {
        if (this.status != ConsumptionSheetStatus.DRAFT) {
            throw new IllegalStateException("Can only submit draft sheets");
        }

        if (consumptionLines.isEmpty()) {
            throw new IllegalStateException("Cannot submit consumption sheet without lines");
        }

        this.status = ConsumptionSheetStatus.SUBMITTED;
    }

    // ✅ Aprobare
    public void approve() {
        if (this.status != ConsumptionSheetStatus.SUBMITTED) {
            throw new IllegalStateException("Can only approve submitted sheets");
        }

        this.status = ConsumptionSheetStatus.APPROVED;

        // ✅ IMPORTANT: Actualizarea stocurilor se face în Domain Service, NU aici!
    }

    // ✅ Respingere
    public void reject(String reason) {
        if (this.status != ConsumptionSheetStatus.SUBMITTED) {
            throw new IllegalStateException("Can only reject submitted sheets");
        }

        if (reason == null || reason.trim().isEmpty()) {
            throw new IllegalArgumentException("Rejection reason is required");
        }

        this.status = ConsumptionSheetStatus.REJECTED;
    }

    // ✅ Calculated fields - totaluri
    @Transient
    public BigDecimal getTotalFeedConsumed() {
        return consumptionLines.stream()
                .filter(line -> line.getConsumable().isFeedType())
                .map(ConsumptionSheetLine::getQuantityConsumed)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    @Transient
    public BigDecimal getTotalWaterConsumed() {
        return consumptionLines.stream()
                .filter(line -> line.getConsumable().getType().name().contains("WATER"))
                .map(ConsumptionSheetLine::getQuantityConsumed)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    @Transient
    public BigDecimal getAverageFeedPerBird() {
        if (birdsAlive == 0) {
            return BigDecimal.ZERO;
        }
        return getTotalFeedConsumed()
                .divide(BigDecimal.valueOf(birdsAlive), 4, RoundingMode.HALF_UP);
    }

    @Transient
    public boolean hasAutoGeneratedLines() {
        return consumptionLines.stream()
                .anyMatch(ConsumptionSheetLine::isAutoGenerated);
    }

    // ✅ Verificare consum minim (alertă dacă prea scăzut)
    @Transient
    public boolean isBelowMinimumConsumption(BigDecimal minPerBird) {
        return getAverageFeedPerBird().compareTo(minPerBird) < 0;
    }

    public ConsumptionSheet(Long id, LocalDateTime createdAt, LocalDateTime updatedAt, ChicksLot lot, LocalDate sheetDate, Integer birdsAlive, ConsumptionSheetStatus status) {
        super(id, createdAt, updatedAt);
        this.lot = lot;
        this.sheetDate = sheetDate;
        this.birdsAlive = birdsAlive;
        this.status = status;
    }
}